//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gCrawler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPolyCrawlerEntities1 : DbContext
    {
        public DBPolyCrawlerEntities1()
            : base("name=DBPolyCrawlerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KeyWord> KeyWords { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Qualifier> Qualifiers { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<WebSite> WebSites { get; set; }
    }
}
