//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gCrawler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualifier
    {
        public int IdQualifier { get; set; }
        public string qualifier1 { get; set; }
        public string project { get; set; }
        public bool positive { get; set; }
    
        public virtual Project Project1 { get; set; }
    }
}
